name: Daily Stock System

on:
  schedule:
    - cron: "0 12 * * *"   # daily auto run (Bangladesh 6PM approx)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 🔥 IMPORTANT for push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Stock System
        run: python scripts/main.py

      - name: Commit & Push Report
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add output/daily-report.json
          git commit -m "auto update report" || echo "no changes"

          git push